#!/usr/bin/env python3
# pyright: reportMissingImports=false

from ev3dev2.motor import OUTPUT_A, OUTPUT_B,OUTPUT_C, OUTPUT_D, MoveTank, MoveSteering, LargeMotor, MediumMotor, SpeedPercent
from ev3dev2.led import Leds
from ev3dev2.button import Button
from ev3dev2.sensor.lego import ColorSensor, UltrasonicSensor
from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4
from ev3dev2.sound import Sound
import time
import threading
from importlib.machinery import SourceFileLoader

Navigation = SourceFileLoader('Navigation', '/home/robot/N_R_C_2_0_2_1/Modules/Navigation').load_module()
Polling = SourceFileLoader('Polling', '/home/robot/N_R_C_2_0_2_1/Modules/Polling').load_module()
Memory = SourceFileLoader('Memory', '/home/robot/N_R_C_2_0_2_1/Modules/Memory').load_module()
Storage = SourceFileLoader('car_storage', '/home/robot/N_R_C_2_0_2_1/Modules/car_storage').load_module()

# Instantiate Brick
leds = Leds()
btn = Button()
spk = Sound()

# Instantiate Sensors
left_ls = ColorSensor(INPUT_2)
right_ls = ColorSensor(INPUT_3)

# Instantiate Motors
lm = LargeMotor(OUTPUT_B)
rm = LargeMotor(OUTPUT_C)

steering = MoveSteering(OUTPUT_B, OUTPUT_C)
tank = MoveTank(OUTPUT_B, OUTPUT_C)

# Threading
m_lock = threading.Lock()

# Min/Max Reflective Value
minRef = 0
maxRef = 50
lls_Ref_black_white = 23
rls_Ref_black_white = 22

# Initialize instances

ctrl = Navigation.Navigate(m_lock, minRef, maxRef, lls_Ref_black_white, rls_Ref_black_white)
mem = Memory.Memory()
store = Storage.Storage(mem, tank)
poll = Polling.Poll(m_lock, minRef, maxRef, ctrl.rm, ctrl.lm, mem, 40.0, 25.0, 18.0, 5.0, False, False, 70, ctrl, store)

left_ls.mode = 'COL-REFLECT'
right_ls.mode = 'COL-REFLECT'


# Start
leds.set_color('LEFT', 'RED')
leds.set_color('RIGHT', 'RED')
print('Ready')
# while not btn.enter:
#     pass
# leds.all_off()

## Run starts
time_start = time.perf_counter()

# Escape base
tank.on_for_degrees(20, 20, 323)
ctrl.turn(turn_right = True, turn_spd = 15, degrees = 200)

# Align with line to collect first 2 batteries
tank.on(20, 20)
time.sleep(0.8)
tank.off()

ctrl.runpid(0.18, 0, 1 ,15, right_light_sensor = False, follow_right_edge = True)  
while not right_ls.reflected_light_intensity > 35:
    pass

ctrl.stop_pid()

tank.on_for_degrees(-10, -10, 53)


# Turn and collect first 2 batteries
ctrl.turn(turn_right = True, turn_spd = 15, degrees = 199)
tank.on(-20, -20)
while not left_ls.reflected_light_intensity > 40:
    pass
tank.off()
ctrl.align(20,2,2, black_white = True, correction_spd = 10, pos_beforeline = False)


store.run_pusher(100, extend = False)

tank.on_for_degrees(20,20, 230) 

store.storage_motor.on_for_degrees(-25, 300)

tank.on_for_degrees(-15,-15, 160)
ctrl.turn(turn_right = False, turn_spd = 20, degrees = 200)

# Align to collect next 2 batteries
ctrl.runpid(0.18, 0, 1 ,15, right_light_sensor = False, follow_right_edge = False)

poll.start_inters_poll(right_light_sensor = True)

while True:
    if poll.intersection == 1: 
        break 
poll.inters_stop()
ctrl.stop_pid()
poll.intersection = 0

tank.on(-10,-10)
while not right_ls.reflected_light_intensity < 15:
        pass
tank.on_for_degrees(10, 10, 105)

# Collect next 2 batteries
ctrl.turn(turn_right = True, turn_spd = 20, degrees = 200)

tank.on(-15, -15)
time.sleep(0.2)
while not right_ls.reflected_light_intensity < 10:
    pass 
while not right_ls.reflected_light_intensity > 40:
    pass
tank.off()

ctrl.align(15,2,3, black_white = True, correction_spd = 10, pos_beforeline = True)

store.pos_alignedto = 3
store.reset_storage(30)
store.storage_motor.on_for_degrees(-30, 220)
tank.on_for_degrees(15, 15, 80)

store.pos_alignedto = 3
store.align_storage(4, 30)
store.storage_motor.on_for_degrees(-30, 320)

tank.on_for_degrees(15, 15, 100)

store.pos_alignedto = 3
store.align_storage(5, 30)

tank.on_for_degrees(10,10,80)
store.storage_motor.on_for_degrees(-25, 130)
tank.on_for_degrees(-20,-20, 30)
while not btn.up:
    pass
store.reset_storage(30)
while not btn.up:
    pass



# Align to collect row of cars
ctrl.turn(turn_right = False, turn_spd = 20, degrees = 200)

while not btn.up:
    pass
store.reset_storage(30)
while not btn.up:
    pass

tank.on(-15,-15)
time.sleep(0.3)
while not left_ls.reflected_light_intensity > 40:
    pass
while not left_ls.reflected_light_intensity < 10:
    pass
tank.off()

tank.on(10,10)
while not left_ls.reflected_light_intensity > 40:
    pass
tank.on_for_degrees(10,10, 18)

ctrl.turn(turn_right = False)
ctrl.align(20,2,3, black_white = True, correction_spd = 10, pos_beforeline = True, target_light_intensity = 20)

# Collect all the car
tank.on_for_degrees(15, 15, 900)

# Align back to the line
tank.on_for_degrees(-30, -30, 850)
ctrl.turn(turn_right = True, turn_spd = 20, degrees = 200)

# Car Parking

# Caculate duration of run
time_end = time.perf_counter()
diff = round(time_end - time_start, 1)
print(diff)

