#!/usr/bin/env python3
# pyright: reportMissingImports=false
# 
from ev3dev2.motor import OUTPUT_A, OUTPUT_B,OUTPUT_C, OUTPUT_D, MoveTank, MoveSteering, LargeMotor, MediumMotor, SpeedPercent
from ev3dev2.led import Leds
from ev3dev2.button import Button
from ev3dev2.sensor.lego import ColorSensor, UltrasonicSensor
from ev3dev2.sensor import INPUT_1, INPUT_2, INPUT_3, INPUT_4
from ev3dev2.sound import Sound
import time
import threading
from importlib.machinery import SourceFileLoader

Navigation = SourceFileLoader('Navigation', '/home/robot/N_R_C_2_0_2_1/Modules/Navigation').load_module()
Polling = SourceFileLoader('Polling', '/home/robot/N_R_C_2_0_2_1/Modules/Polling').load_module()
Memory = SourceFileLoader('Memory', '/home/robot/N_R_C_2_0_2_1/Modules/Memory').load_module()
Storage = SourceFileLoader('car_storage', '/home/robot/N_R_C_2_0_2_1/Modules/car_storage').load_module()

# Instantiate Brick
leds = Leds()
btn = Button()
spk = Sound()

# Instantiate Sensors
left_ls = ColorSensor(INPUT_2)
right_ls = ColorSensor(INPUT_3)

lls_Ref_betwline = 23
rls_Ref_betwline = 23

# Instantiate Motors
lm = LargeMotor(OUTPUT_B)
rm = LargeMotor(OUTPUT_C)

steering = MoveSteering(OUTPUT_B, OUTPUT_C)
tank = MoveTank(OUTPUT_B, OUTPUT_C)

# Threading
m_lock = threading.Lock()

# Min/Max Reflective Value
minRef = 0
maxRef = 50

# backward PID constants
fwd_kp = 0.31
fwd_kd = 0.60
fwd_pid_spd = 20

# forward PID constants
bwd_kp = 0.35
bwd_kd = 0.8
bwd_pid_spd = 20

# Initialize instances
ctrl = Navigation.Navigate(m_lock, minRef, maxRef, lls_betw_line =  lls_Ref_betwline, rls_betw_line = rls_Ref_betwline) 
mem = Memory.Memory()
store = Storage.Storage(mem, tank)
poll = Polling.Poll(m_lock, minRef, maxRef, ctrl.rm, ctrl.lm, mem, 40.0, 25.0, 18.0, 5.0, False, False, 70, ctrl, store)

run_eject = True
run_collect = False

def resetRobot():
    store.reset_storage(30)
    store.storage_motor.on_for_degrees(-100, 90)
    store.extend_retract(100, retract = False)
    store.storage_motor.on_for_degrees(100, 90)

def pauseloop():
    while not btn.up:
        if btn.down:
            resetRobot()
        pass

'''

COLLECTING CARS

'''
'''
## Run starts
time_start = time.perf_counter()

# Escape base
tank.on_for_degrees(20, 20, 200)
ctrl.turn(turn_right = True, turn_spd = 13, degrees = 184)

# Align with line to collect first 2 batteries

tank.on(20, 20)
time.sleep(0.8)

while not right_ls.reflected_light_intensity > 35:
    pass
while not right_ls.reflected_light_intensity < 10:
    pass
while not right_ls.reflected_light_intensity > 35:
    pass
tank.off()
ctrl.align(10,2.5,2, black_white = True, correction_spd = 10, pos_beforeline = False, timeout = False)
tank.on_for_degrees(10, 10, 40)

ctrl.turn(turn_right = False, turn_spd = 13, degrees = 184)

store.storage_motor.on_for_degrees(-100, 90)
store.extend_retract(100, extend = False)
store.storage_motor.on_for_degrees(100, 90)

store.align_storage(6, 20)
tank.on_for_degrees(10,10, 60)
ctrl.align(10,2.5,2, black_white = False, correction_spd = 10, pos_beforeline = True, timeout = False)


# Collect 1st car
tank.on_for_degrees(10,10, 160)

# Collect 2nd car
store.align_storage(5, 15, from_mid = False)
tank.on_for_degrees(10,10, 148)


# # Collect 3rd car
store.align_storage(4, 15, from_mid = False)
tank.on_for_degrees(10,10, 148)

# Collect 4th car
store.align_storage(3, 15, from_mid = False)
tank.on_for_degrees(10,10, 148)

# Collect 5th car
store.align_storage(2, 15, from_mid = False)
tank.on_for_degrees(10,10, 148)

# Collect 6th car
store.align_storage(1, 15, from_mid = False)
tank.on_for_degrees(10,10, 148)
store.reset_storage(30)
'''
store.storage_motor.on_for_degrees(-100, 90)
store.extend_retract(100, extend = False)
store.storage_motor.on_for_degrees(100, 90)

# Return to line
tank.on(-20, -20)
while right_ls.reflected_light_intensity > 10:
    pass
tank.off()
ctrl.align(20,2.5,2, black_white = True, correction_spd = 10, pos_beforeline = False, timeout = False)
tank.on_for_degrees(-20,-20, 50)
steering.on_for_degrees(50, 20, 380)

''' 

STARTING RUN ON BOTTOM LANE

'''

# Start


mem.setRow("middle")

if mem.currentRow == "middle":
    ctrl.runpid(fwd_kp, 0, fwd_kd ,fwd_pid_spd, right_light_sensor = True, follow_right_edge = True, scaling = False)
    time.sleep(2.0)
    poll.start_inters_poll(right_light_sensor = False)

# poll.start_us_poll()

restarted = False
turn_at_0inters = True
temp = 0
rerun = False

while True:
    if not poll.intersection == 0 and poll.turning:
        print('poll.turning ran')
        poll.inters_stop()
        ctrl.stop_pid()

        # Charged Car
        if poll.slot_item == "car" and ((poll.pillar_right == True and store.check_vacancy([1, 2, 3, 4])) or (poll.pillar_right == False and store.check_vacancy([3, 4, 5, 6])) or poll.pillar_right == None) and run_collect:
            
            # Align horizontally to intersection
            tank.on_for_degrees(10, 10, 30)
            tank.on(-10, -10)
            while not right_ls.reflected_light_intensity < 15:
                pass
            tank.off()
            tank.on_for_degrees(10, 10, 10)
            ctrl.align(10,10,2, black_white = True, correction_spd = 10, pos_beforeline = False, timeout = False)
            pauseloop()

            # Turn 
            turning_constant = 385.5
            if poll.turn_right:
                if poll.pillar_right == True:
                    steering.on_for_degrees(-75, 20, turning_constant*3*0.75)
                else:
                    tank.on_for_degrees(10, 10, 150)
                    steering.on_for_degrees(-50, -20, turning_constant)
            else:
                if poll.pillar_right == True:
                    steering.on_for_degrees(100, 20, turning_constant*3*0.75)
                else:
                    tank.on_for_degrees(10, 10, 150)
                    steering.on_for_degrees(75, -20, turning_constant)
            # ctrl.turn(turn_right = poll.turn_right)
            pauseloop()
            # collect car
            '''
            def align(self,
            start_spd,
            maxduration,
            marginoferror,
            target_light_intensity = None,
            black_white = True,
            correction_spd = None,
            pos_beforeline = True,
            timeout = True):
            '''
            
            # def align_storage(self, pos, spd, from_mid = True):
            pauseloop()
            store.align_storage(6, 30)
            pauseloop()
            tank.on_for_degrees(10, 10, 350)
            pauseloop()
            # ctrl.catch_line(20, turn_right = not poll.turn_right)

        # Vacant 
        if poll.slot_item == "vacant" and run_eject:
            eject_car = False
            print('pillar_right' + str(poll.pillar_right))
            print('inters' + str(poll.intersection))
            if poll.pillar_right == None:
                eject_car = store.find_car(colour=poll.slot_color, left_side = True, right_side = True)
            else:
                eject_car = store.find_car(colour=poll.slot_color, left_side = not poll.pillar_right, right_side = poll.pillar_right)
            print('eject_car' + str(eject_car))
            if eject_car:
                if poll.pillar_right == True:
                    tank.on_for_degrees(-10, -10, 70)
                    tank.on_for_degrees(10, 10, 20)
                elif poll.pillar_right == False:
                    # tank.on_for_degrees(-10, -10, 10)
                    tank.on_for_degrees(10, 10, 10)
                ctrl.turn(turn_right = poll.turn_right)
                tank.on_for_degrees(10, 10, 35)
                store.eject_car(25)
                tank.on_for_degrees(-10, -10, 40)
                pauseloop()
                ctrl.turn(turn_right = not poll.turn_right)
                ctrl.align(10,1,2, black_white = True, correction_spd = 10, pos_beforeline = False, timeout = True)
                pauseloop()
        poll.turn_right  = None
        poll.turning = False

        # Continue 
        if mem.currentRow == "bottom" or mem.currentRow == "middle":
            if poll.invert_memory:
                ctrl.runpid(bwd_kp, 0, bwd_kd ,bwd_pid_spd, right_light_sensor = True, follow_right_edge = True, forward= False, scaling = False)
            else:
                ctrl.runpid(fwd_kp, 0, fwd_kd ,fwd_pid_spd, right_light_sensor = True, follow_right_edge = True, forward = True, scaling = False)
            time.sleep(1)
            poll.start_inters_poll(right_light_sensor = False)

        
        elif mem.currentRow == "top":
            if poll.invert_memory:
                ctrl.runpid(bwd_kp, 0, bwd_kd ,bwd_pid_spd, right_light_sensor = False, follow_right_edge = False, forward= False, scaling = False)
            else:
                ctrl.runpid(fwd_kp, 0, fwd_kd ,fwd_pid_spd, right_light_sensor = False, follow_right_edge = False, forward = True, scaling = False)
            time.sleep(1)
            poll.start_inters_poll(right_light_sensor = True)

    if poll.intersection == 4 and not restarted:
        poll.inters_stop()
        time.sleep(1)
        ctrl.stop_pid()
        poll.intersection = poll.intersection + 1
        mem.changeCol(1)
        restarted = True
        print('pid stopped')
        

        if mem.currentRow == "top":
            poll.invert_memory = True
            mem.currentRow = "top"
            ctrl.runpid(bwd_kp, 0, bwd_kd ,bwd_pid_spd, right_light_sensor = False, follow_right_edge = False, forward = False, scaling = False)
            poll.start_inters_poll(right_light_sensor = True)

        elif mem.currentRow == "middle":
            poll.invert_memory = True
            mem.currentRow = "bottom"
            ctrl.runpid(bwd_kp, 0, bwd_kd ,bwd_pid_spd, right_light_sensor = True, follow_right_edge = True, forward = False, scaling = False)
            poll.start_inters_poll(right_light_sensor = False)

    if poll.intersection == 0 and poll.invert_memory:
        ctrl.stop_pid()
        poll.inters_stop()

        if mem.currentRow == "bottom":
            
            # Move Robot from bottom/middle row to top/middle row
            pauseloop()
            steering.on_for_degrees(-50, 20, 380)
            tank.on_for_degrees(-10,-10, 100)

            pauseloop()
            ctrl.align(20,2.5,2, black_white = True, correction_spd = 10, pos_beforeline = True, timeout = False)
            
            pauseloop()

            poll.intersection = -1
            ctrl.runpid(fwd_kp, 0, fwd_kd ,fwd_pid_spd, right_light_sensor = False, follow_right_edge = False, forward=True, scaling = False)
            time.sleep(0.6)
            poll.start_inters_poll(right_light_sensor = True)

            while not poll.intersection == 0:
                pass
            poll.inters_stop()
            ctrl.stop_pid()
            
            # Align to top/middle row

            ctrl.turn(turn_right = True)

            poll.invert_memory = False
            mem.currentRow = 'top'
            ctrl.runpid(fwd_kp, 0, fwd_kd ,fwd_pid_spd, right_light_sensor = False, follow_right_edge = False, forward=True)
            time.sleep(0.6)
            poll.start_inters_poll(right_light_sensor = True)

            restarted = False
        elif mem.currentRow == "top":
            steering.on_for_degrees(0, -25, 190)

    if btn.enter:
        ctrl.stop_pid()
        poll.inters_stop()
        resetRobot()
        break
